package com.ailaji.manage.entity;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	public final static String ID = "id";
	public final static String ACCOUNT = "account";
	public final static String PASSWORD = "password";
	public final static String USERNAME = "username";
	public final static String AGE = "age";
	public final static String SEX = "sex";

	private String id;
	private String account;
	private String password;
	private String username;
	private Integer age;
	private String sex;

	public User() {
	}

	public User(String id, String account) {
		this.id = id;
		this.account = account;
	}
	public User(String id, String account, String password, String username,
			Integer age, String sex) {
		this.id = id;
		this.account = account;
		this.password = password;
		this.username = username;
		this.age = age;
		this.sex = sex;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

}
