package com.ailaji.manage.entity;

import java.util.Date;

/**
 * UserResource generated by hbm2java
 */
public class UserResource implements java.io.Serializable {

	public final static String ID = "id";
	public final static String NAME = "name";
	public final static String THUMBNAIL = "thumbnail";
	public final static String TYPE = "type";
	public final static String TAG = "tag";
	public final static String CREATETIME = "createTime";
	public final static String URL = "url";
	public final static String USERID = "userId";

	private String id;
	private String name;
	private String thumbnail;
	private int type;
	private String tag;
	private Date createTime;
	private String url;
	private String userId;

	public UserResource() {
	}

	public UserResource(String id, String name, int type, Date createTime,
			String url, String userId) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.createTime = createTime;
		this.url = url;
		this.userId = userId;
	}
	public UserResource(String id, String name, String thumbnail, int type,
			String tag, Date createTime, String url, String userId) {
		this.id = id;
		this.name = name;
		this.thumbnail = thumbnail;
		this.type = type;
		this.tag = tag;
		this.createTime = createTime;
		this.url = url;
		this.userId = userId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getThumbnail() {
		return this.thumbnail;
	}

	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
